version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "8000:5000"
    volumes:
      - ./app:/app
    environment:
      FLASK_ENV: development
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro